version: "3.1"

services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: casbin
    command: postgres -c listen_addresses='*'

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: casbin
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
